#! /bin/bash
## usage: trac_2_tckgen -t 12 -data fsp

while [ $1 != -- ] ; do
  case $1 in
    -t)
      nthreads=$2;
      shift;;
    -data)
      dir1=$2
      shift;;
   esac
    shift
done

he=/ifs/scratch/pimri/posnerlab/1anal/Hellerstein
jobdir=${he}/code/he/job
logdir=${he}/code/he/job

CMD1_batch=$logdir/batch${nbatch}_5ttgen
CMD2_batch=$logdir/batch${nbatch}_tckgen

rm -rf $CMD1_batch
rm -rf $CMD2_batch

nthreadsX2=$((${nthreads}*2))


subjectlist=$he/$dir1/list_dtisubject
for s in `cat $subjectlist`
do



CMD1=$logdir/cmd.5ttgen.${s}
rm -rf $CMD1

echo "#!/bin/bash
source ~/.bashrc
FREESURFER_HOME=$work/freesurfer_dev/freesurfer
source /ifs/scratch/pimri/posnerlab/freesurfer_dev/freesurfer/FreeSurferEnv.sh
ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=$nthreadsX2
SUBJECT=${s}
cd ${he}/${dir1}/${s}/dmri2
mkdir xfm

### 1. flirt 
echo *****1. NOW GENERATING ANAT2DIFF.FLT.MAT *****
mri_convert ../mri/brain.mgz brain_anat_orig.nii.gz
sleep 5
/ifs/scratch/pimri/posnerlab/freesurfer_dev/freesurfer/bin/flip4fsl  brain_anat_orig.nii.gz brain_anat.nii.gz
sleep 5
mrconvert mr_meanb0.mif.gz mr_meanb0.nii.gz -force
sleep 5
flirt -in brain_anat.nii.gz -ref mr_meanb0.nii.gz -out brain_anat2diff -omat anat2diff.flt.mat -v
sleep 5


### 2.5TTGEN
echo ***** 2. NOW 5TTGEN *****
mri_convert ../mri/T1.mgz /tmp/tmp.nii.gz && /ifs/scratch/pimri/posnerlab/freesurfer_dev/freesurfer/bin/flip4fsl /tmp/tmp.nii.gz T1_flip.nii.gz
sleep 5
flirt -in T1_flip.nii.gz -out T1_2diff_flt.nii.gz -ref mr_meanb0.nii.gz -applyxfm -init anat2diff.flt.mat -v
sleep 5
5ttgen fsl T1_2diff_flt.nii.gz 5tt2.mif.gz -force -nthreads $nthreadsX2
mrconvert 5tt2.mif.gz 5tt2.nii.gz -force
sleep 5
5tt2gmwmi 5tt2.mif.gz 5tt2_gmwmi_mask.mif.gz -nthreads $nthreadsX2 -force
sleep 5



### APARC+ASEG to diff
echo ***** 3. NOW CONVERTING APARC+ASEG TO DIFF *****
for im in aparc+aseg aparc.a2009s+aseg
do
   echo ****NOW CONVERTING MGZ TO NII
   mri_convert ../mri/\${im}.mgz \${im}.nii.gz
   sleep 5
   
   echo ****FLIPING FOR FSL
   /ifs/scratch/pimri/posnerlab/freesurfer_dev/freesurfer/bin/flip4fsl \${im}.nii.gz \${im}_flip.nii.gz
   sleep 5
   
   echo ****NOW FLIRTING
   flirt -in \${im}_flip.nii.gz -out \${im}_2_diff_flt.nii.gz -ref mr_meanb0.nii.gz -applyxfm -init anat2diff.flt.mat -interp nearestneighbour
   sleep 5
done



### labelconvert for aparc+aseg and aparc.a2009+aseg
labelconvert aparc+aseg_diff_synants.nii.gz $FREESURFER_HOME/FreeSurferColorLUT.txt /ifs/scratch/pimri/posnerlab/app/mrtrix3/src/connectome/tables/fs_default.txt nodes_aparc+aseg.mif.gz -force
sleep 5

labelconvert aparc.a2009s+aseg_diff_synants.nii.gz $FREESURFER_HOME/FreeSurferColorLUT.txt /ifs/scratch/pimri/posnerlab/app/mrtrix3/src/connectome/tables/fs_a2009s.txt nodes_aparc.a2009s+aseg.mif.gz -force
sleep 5

############
" >$CMD1


#batch submission
echo $CMD1 >> $CMD1_batch
done

#prepid=`$code/fsl_sub_hpc_3 -s smp,$nthreads -l $logdir -t ${CMD1_batch}`
echo ${CMD1_batch}

for s in `cat $subjectlist`
do
   CMD2=$logdir/cmd.tckgensift.${s}
   rm -rf $CMD2

   echo "#!/bin/bash
   source ~/.bashrc
   ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=$nthreadsX2
   echo NOW WARPING FOR SUBJECT ${s}
   SUBJECT=${s}
   cd ${he}/${dir1}/${s}/dmri2
#### tckgen
rm -rf mr_track_20M.tck
if [ -e mr_track_10M_SIFT.tck ]; then
tracknum=\`tckinfo mr_track_10M_SIFT.tck | grep max_num_tracks | grep -o 10000000\`
  if [ \$tracknum != 10000000 ]; then
  tckgen WM_FODs.mif.gz /tmp/mr_track_20M.tck -act 5tt.mif.gz -backtrack -crop_at_gmwmi -seed_dynamic WM_FODs.mif.gz -maxlength 250 -minlength 30 -number 20M -force -nthreads $nthreadsX2
  tcksift -act 5tt.mif.gz /tmp/mr_track_20M.tck WM_FODs.mif.gz mr_track_10M_SIFT.tck -term_number 10M -force -nthreads $nthreadsX2 && echo 'sift done'*******
  else 
  echo 'sift done'*******
  fi
else  
tckgen WM_FODs.mif.gz /tmp/mr_track_20M.tck -act 5tt.mif.gz -backtrack -crop_at_gmwmi -seed_dynamic WM_FODs.mif.gz -maxlength 250 -minlength 30 -number 20M -force -nthreads $nthreadsX2
tcksift -act 5tt.mif.gz /tmp/mr_track_20M.tck WM_FODs.mif.gz mr_track_10M_SIFT.tck -term_number 10M -force -nthreads $nthreadsX2 && echo 'sift done'*******
fi
#### tck2connectome
for im in aparc+aseg aparc.a2009s+aseg
do
tck2connectome -force -zero_diagonal -nthreads $nthreadsX2 mr_track_10M_SIFT.tck nodes_\${im}.mif.gz mr_sift_10M_connectome_\${im}_count.csv 
tck2connectome -force -zero_diagonal -scale_length -stat_edge mean -nthreads $nthreadsX2 mr_track_10M_SIFT.tck nodes_\${im}.mif.gz mr_sift_10M_connectome_\${im}_length.csv 
tck2connectome -force -zero_diagonal -scale_invnodevol -nthreads $nthreadsX2 mr_track_10M_SIFT.tck nodes_\${im}.mif.gz mr_sift_10M_connectome_\${im}_volumeadj.csv 
done
### save scratch space
#      if [ -e mr_sift_10M_connectome_aparc+aseg_count.csv ] ; then rm mr_track_100M.tck 
#      else echo SIFT WAS NOT SUCCESSFUL
#      fi
      
echo "END OF TCKGEN AND SIFT"
" > $CMD2
echo $CMD2 >> $CMD2_batch
chmod +x $CMD2

done

#$code/fsl_sub_hpc_36 $monk/data/cmd/cmd2_${s}  
#echo $jobid >> $monk/data/cmd/jobid

echo $code/fsl_sub_hpc_3 -N connectome -s smp,$nthreads -j $prepid -l $logdir -t ${CMD2_batch}
