#!/bin/bash
%% reset LD_LIBRARY_PATH

list=$1
threads=6
threadsX2=$((${threads}*2))

IDP=/ifs/scratch/pimri/posnerlab/1anal/IDP

CMD_batch=/ifs/scratch/pimri/posnerlab/1anal/IDP/code/idp/job/cmd1.batch.trac.${list}
rm $CMD_batch

for s in `cat $IDP/data/$list`
do
CMD=/ifs/scratch/pimri/posnerlab/1anal/IDP/code/idp/job/cmd1.trac.${s}
rm $CMD

cat<<EOC >$CMD
workingdir=/ifs/scratch/pimri/posnerlab/1anal/IDP/fs/${s}/dmri2
if [ ! -e $workingdir ]; then mkdir $workingdir; fi
cd $workingdir

#%% 1. setup %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
rawdti=$IDP/data/$s/dti.nii.gz
rawbvec=$IDP/data/$s/dti.bvec_tp
rawbval=$IDP/data/$s/dti.bval_tp

cp $rawdti ./
cp $rawbvec ./
cp $rawbval ./

%% 2. DWI processing2-converting nifti to mif%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if [ ! -e mr_fod.mif.gz ];then
    mrconvert dti.nii.gz -force mr_dwi.mif.gz -fslgrad dti.bvec_tp dti.bval_tp -datatype float32 -stride 0,0,0,1 -nthreads $threadsX2
fi

%% 3. denoising
if [ ! -e mmr_dwi_denoised.mif.gz ];then
    dwidenoise mr_dwi.mif.gz -force mr_dwi_denoised.mif.gz -nthreads $threadsX2
fi

%% 4. dwipreproc -eddy current
if [ ! -e mr_dwi_denoised_preproc.mif.gz ];then
    dwipreproc PA mr_dwi_denoised.mif.gz -force mr_dwi_denoised_preproc.mif.gz -rpe_none -nthreads $threadsX2
fi

%% 5. mask and bias field correction
if [ ! -e mr_eroded_mask.mif.gz ]; then
     dwi2mask mr_dwi_denoised_preproc.mif.gz - | maskfilter - erode -npass 7 -force mr_eroded_mask.mif.gz -nthreads $threadsX2
fi

%% 6. bias field correction
if [ ! -e mr_dwi_denoised_preproc_biasCorr.mif.gz ]; then
     dwibiascorrect mr_dwi_denoised_preproc.mif.gz -force mr_dwi_denoised_preproc_biasCorr.mif.gz -ants -mask mr_eroded_mask.mif.gz -fslgrad dti.bvec_tp dti.bval_tp -nthreads $threadsX2
fi


%% 7. generating b0 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if [ ! -e mr_meanb0.mif.gz ];then
     dwiextract mr_dwi_denoised_preproc_biasCorr.mif.gz - -bzero -nthreads $threadsX2 | mrmath - mean -force mr_meanb0.mif.gz -axis 3 -nthreads $threadsX2
fi

%% 8. upsampling %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
for im in mr_dwi_denoised_preproc_biasCorr mr_eroded_mask mr_meanb0;
do 
     if [ ! -e ${im}_upsample.mif.gz ];then
     mrresize ${im}.mif.gz -scale 2.0 -force ${im}_upsample.mif.gz -nthreads $threadsX2
     fi
done


%% 9. dwi2response-subject level %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if [ ! -e response_wm.txt ]; then
    dwi2response dhollander -mask mr_eroded_mask.mif.gz -voxels mr_voxels_eroded.mif.gz mr_dwi_denoised_preproc_biasCorr.mif.gz response_wm.txt response_gm.txt response_csf.txt -force -nthreads $threadsX2
fi


%% FOD%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% make sure to use "DILATED MASK" for FOD generation
if [ ! -e mr_dilate_mask.mif.gz ];then
    dwi2mask mr_dwi_denoised_preproc_biasCorr.mif.gz - | maskfilter - dilate -npass 5 -force mr_dilate_mask.mif.gz -nthreads $threadsX2
fi

if [ ! -e WM_FODs.mif.gz ];then
   dwi2fod msmt_csd mr_dwi_denoised_preproc_biasCorr.mif.gz response_wm.txt WM_FODs.mif.gz response_gm.txt gm.mif.gz response_csf.txt csf.mif.gz -mask mr_dilate_mask.mif.gz -force -nthreads $threadsX2
fi

if [ ! -e tissueRGB.mif.gz ]; then
   mrconvert WM_FODs.mif.gz - -coord 3 0 | mrcat csf.mif.gz gm.mif.gz - tissueRGB.mif.gz -axis 3
fi


echo "I THINK EVERYTHING IS DONE BY NOW"
EOC

chmod +x $CMD
echo $CMD>>$CMD_batch
done

### batch submission

echo $CMD_batch
echo $code/fsl_sub_hpc_3 -s smp,$threads -l /ifs/scratch/pimri/posnerlab/1anal/IDP/code/idp/job -t $CMD_batch



